spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-local-info.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:poorlex

  h2:
    console:
      enabled: true
      
logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: INFO
    org.springframework.security: DEBUG
