jwt:
  token:
    secret-key: localtestscretkeylocaltestscretkeylocaltestscretkey
    access-expire-length: 604800000 # 7 일

schedules:
  battle-start:
    cron: "0 * * * * MON-FRI" # 매 분 0초 마다
  battle-end:
    cron: "30 * * * * MON-FRI" # 매 분 30 초마다
