spring:
  profiles:
    active: local

  output:
    ansi:
      enabled: always

  config:
    import: classpath:secure/application.yml

server:
  protocol: http
  host: localhost
  port: 8080
  announce-port: 8080
