create table battle
(
    id                        bigint generated by default as identity,
    name                      varchar(255),
    introduction              varchar(255),
    image_url                 text,
    budget                    bigint,
    max_size                  integer,
    start_time                timestamp(6),
    end_time                  timestamp(6),
    status                    varchar(255) check (status in ('RECRUITING',
                                                             'RECRUITING_FINISHED',
                                                             'PROGRESS',
                                                             'COMPLETE')),
    is_battle_success_counted boolean,
    primary key (id)
);

create table battle_notification
(
    id        bigint generated by default as identity,
    content   varchar(255),
    battle_id bigint,
    image_url text,
    primary key (id)
);

create table battle_participant
(
    id        bigint generated by default as identity,
    battle_id bigint,
    member_id bigint,
    role      varchar(255) check (role in ('MANAGER', 'NORMAL_PLAYER')),
    primary key (id)
);

create table battle_history
(
    id                          bigint generated by default as identity,
    member_id                   bigint,
    battle_name                 varchar(255),
    battle_image_url            varchar(255),
    battle_difficulty           varchar(255) check (battle_difficulty in ('EASY', 'NORMAL', 'HARD')),
    battle_max_participant_size integer not null,
    battle_end                  date,
    member_battle_rank          integer not null,
    member_budget_left          bigint  not null,
    member_earned_point         integer not null,
    successed                   boolean not null,
    primary key (id)
);

create table battle_alarm
(
    id         bigint generated by default as identity,
    battle_id  bigint,
    member_id  bigint,
    type       varchar(255) check (type in
                                   ('EXPENDITURE_CREATED',
                                    'EXPENDITURE_NEEDED',
                                    'OVER_BUDGET',
                                    'ZERO_EXPENDITURE',
                                    'PARTICIPANT_ESCAPE',
                                    'BATTLE_NOTIFICATION_CHANGED')),
    created_at timestamp(6),
    primary key (id)
);

create table battle_alarm_view_history
(
    id             bigint generated by default as identity,
    battle_id      bigint,
    member_id      bigint,
    last_view_time timestamp(6),
    primary key (id)
);

create table alarm_reaction
(
    id         bigint generated by default as identity,
    alarm_id   bigint,
    member_id  bigint,
    content    varchar(255),
    type       varchar(255) check (type in ('PRAISE', 'SCOLD')),
    created_at timestamp(6),
    primary key (id)
);

create table member
(
    id                    bigint generated by default as identity,
    oauth2registration_id varchar(255) check (oauth2registration_id in ('KAKAO', 'APPLE')),
    oauth_id              varchar(100),
    description           varchar(300),
    nickname              varchar(255),
    constraint idx_registrationId_oauthId unique (oauth2registration_id, oauth_id),
    primary key (id)
);

create table expenditure
(
    id          bigint generated by default as identity,
    description varchar(255),
    amount      bigint,
    date        date,
    member_id   bigint,
    primary key (id)
);

create table expenditure_image
(
    id             bigint generated by default as identity,
    url            text,
    expenditure_id bigint,
    primary key (id)
);

create table friend
(
    id               bigint generated by default as identity,
    first_member_id  bigint,
    second_member_id bigint,
    primary key (id)
);

create table member_point
(
    id        bigint generated by default as identity,
    point     integer,
    member_id bigint,
    primary key (id)
);
