== 배틀 알림 API

=== 배틀 알림 조회 ( 기본 알림 일 때 )

operation::battle-alarm-find-basic[snippets='http-request']
operation::battle-alarm-find-basic[snippets='request-fields']
operation::battle-alarm-find-basic[snippets='http-response']
operation::battle-alarm-find-basic[snippets='response-fields']

=== 배틀 알림 조회 ( 투표일 때 )

operation::battle-alarm-find-vote[snippets='http-request']
operation::battle-alarm-find-vote[snippets='request-fields']
operation::battle-alarm-find-vote[snippets='http-response']
operation::battle-alarm-find-vote[snippets='response-fields']

=== 배틀 알림 조회 ( 투표 참가표일 떄 )

operation::battle-alarm-find-voting-paper[snippets='http-request']
operation::battle-alarm-find-voting-paper[snippets='request-fields']
operation::battle-alarm-find-voting-paper[snippets='http-response']
operation::battle-alarm-find-voting-paper[snippets='response-fields']

=== 배틀 알림 조회 ( 알림 반응일 때 )

operation::battle-alarm-find-reaction[snippets='http-request']
operation::battle-alarm-find-reaction[snippets='request-fields']
operation::battle-alarm-find-reaction[snippets='http-response']
operation::battle-alarm-find-reaction[snippets='response-fields']

=== 배틀 알림 미확인 개수 조회

operation::battle-unchecked-alarm-count[snippets='http-request']
operation::battle-unchecked-alarm-count[snippets='http-response']
operation::battle-unchecked-alarm-count[snippets='response-fields']

== 배틀 알림 반응 api

=== 배틀 알림 반응 생성

operation::battle-alarm-reaction-create[snippets='http-request']
operation::battle-alarm-reaction-create[snippets='request-fields']
operation::battle-alarm-reaction-create[snippets='http-response']

== 회원 알림 API

=== 회원 알림 조회

operation::member-alarm-find[snippets='http-request']
operation::member-alarm-find[snippets='request-fields']
operation::member-alarm-find[snippets='http-response']
operation::member-alarm-find[snippets='response-fields']
