== 목표 API

=== 회원 목표 등록

operation::goal-create[snippets='http-request']
operation::goal-create[snippets='request-fields']
operation::goal-create[snippets='http-response']

=== 회원 목표 수정

operation::goal-update[snippets='http-request']
operation::goal-update[snippets='request-fields']
operation::goal-update[snippets='http-response']

=== 회원 목표 삭제

operation::goal-delete[snippets='http-request']
operation::goal-delete[snippets='http-response']

=== 회원 목표 ID 조회

operation::goal-find-ids[snippets='http-request']
operation::goal-find-ids[snippets='http-response']
operation::goal-find-ids[snippets='response-fields']

=== 회원 목표 조회 [ 진행 중 ]

operation::goal-find-progress[snippets='http-request']
operation::goal-find-progress[snippets='request-fields']
operation::goal-find-progress[snippets='http-response']
operation::goal-find-progress[snippets='response-fields']

=== 회원 목표 조회 [ 완료 ]

operation::goal-find-finish[snippets='http-request']
operation::goal-find-finish[snippets='request-fields']
operation::goal-find-finish[snippets='http-response']
operation::goal-find-finish[snippets='response-fields']

=== 목표 타입 목록 조회

operation::goal-find-types[snippets='http-request']
operation::goal-find-types[snippets='http-response']
operation::goal-find-types[snippets='response-fields']
