# workflow의 이름
name: Docker Build

# 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
on:
  pull_request:
    branches: [ main, dev ] # main, dev pull request 가 closed 될 때 실행됩니다.
    types: [ closed ]

permissions: write-all

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
jobs:
  docker-build:
    needs: gradle-build # gradle-build 이후에 실행됩니다.
    name: docker-build
    if: github.event.pull_request.merged == true # 성공적으로 merge 된 경우에만 실행합니다.
    runs-on: ubuntu-latest

    steps:
      - name: Download Jar file
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: build/libs

      - name: Download Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: poorlexofficial/poorlex-backend
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}