# workflow의 이름
name: Gradle Build

# 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
on:
  pull_request:
    branches: [ main, dev ] # main, dev pull request 가 closed 될 때 실행됩니다.
    types: [ closed ]

permissions: write-all

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
jobs:
  gradle-build:
    name: gradle-build
    if: github.event.pull_request.merged == true # 성공적으로 merge 된 경우에만 실행합니다.
    runs-on: ubuntu-latest

    steps:
      # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE에서 저장소를 체크아웃합니다.
      - name: Pull Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # 자바를 설치하는 명렁어
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test -x copyDocument
        shell: bash

      - name: Upload Jar file
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/*.jar
          retention-days: 3

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: Dockerfile
          path: Dockerfile
          retention-days: 3